DROP TABLE IF EXISTS "paper";
DROP TABLE IF EXISTS class;
DROP TABLE IF EXISTS "user";

CREATE TABLE "user" (
   id SERIAL PRIMARY KEY,
   username TEXT UNIQUE NOT NULL,
   password TEXT NOT NULL
 );

 CREATE TABLE class (
   id SERIAL PRIMARY KEY,
   user_id INTEGER NOT NULL,
   class_name TEXT NOT NULL,
   FOREIGN KEY (user_id) REFERENCES "user"(id)
 );

CREATE TABLE paper (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  abstract TEXT NOT NULL,
  link TEXT NOT NULL,
  class_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES "user"(id),
  FOREIGN KEY (class_id) REFERENCES class(id)
);