DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS paper;
DROP TABLE IF EXISTS class;

CREATE TABLE paper (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  abstract TEXT NOT NULL,
  link TEXT NOT NULL,
  class_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (class_id) REFERENCES class (id)
);

CREATE TABLE user (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   username TEXT UNIQUE NOT NULL,
   password TEXT NOT NULL
 );

 CREATE TABLE class (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   user_id INTEGER NOT NULL,
   class_name TEXT NOT NULL,
   FOREIGN KEY (user_id) REFERENCES user (id)
 );